#overlays/prod/patch-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  annotations:
    # [리팩토링] prod 전용 IRSA Role. dev role-arn 을 물면 권한 격리가 깨짐
    eks.amazonaws.com/role-arn: "arn:aws:iam::495599735720:role/team3-prod-app-irsa-role"