apiVersion: v1
kind: ConfigMap
metadata:
  name: foldy-app-config
  namespace: app
  labels:
    app: foldy
data:
  APP_ENV: "dev"
  LOG_LEVEL: "DEBUG"

  # AWS
  AWS_REGION: "ap-northeast-2"
  S3_BUCKET: "tfstate-lionkdt5-team3"

  # 체크필요
  SPRING_DATASOURCE_URL: "jdbc:mysql://dev-foldy-db-server.cne4w2cys26c.ap-northeast-2.rds.amazonaws.com:3306/foldy"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  # JWT
  JWT_EXPIRATION: "3600000"
