apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  annotations:
    # Pod가 AWS 리소스(S3 등)에 접근할 때 사용할 IAM Role
    eks.amazonaws.com/role-arn: "arn:aws:iam::495599735720:role/team3-dev-app-irsa-role"